### ISSUE TITLE
Allow to provide channels list in the configuration file

### ISSUE THREAD

**Issue by agonzalezro** [agonzalezro/botella#3]
For example:

```
adapters:
  - name: slack
    environment:
      key: xoxb-xxx
    channels:
      - #general
      - #random
```
